In [196]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [197]:
import math

In [198]:
df=pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [199]:
median_s=math.floor(df['test_score(out of 10)'].median())
median_s


8

In [200]:

df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(median_s)
df


experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [201]:
import pandas as pd

# Step 2: Define the mapping dictionary
word_to_num = {
    'zero': 0, 'one': 1, 'two': 2, 'three': 3, 'four': 4,
    'five': 5, 'six': 6, 'seven': 7, 'eight': 8, 'nine': 9,
    'ten': 10, 'eleven': 11, 'twelve': 12, 'thirteen': 13, 'fourteen': 14,
    'fifteen': 15, 'sixteen': 16, 'seventeen': 17, 'eighteen': 18, 'nineteen': 19,
    'twenty': 20, 'thirty': 30, 'forty': 40, 'fifty': 50,
    'sixty': 60, 'seventy': 70, 'eighty': 80, 'ninety': 90
}
d=pd.DataFrame(df['experience'])

# Step 3: Convert the words to numbers
df_numeric = d.applymap(word_to_num.get)
print(df_numeric)

   experience
0         NaN
1         NaN
2         5.0
3         2.0
4         7.0
5         3.0
6        10.0
7        11.0


In [202]:
df['experience']=df_numeric
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    8.0                           7      72000
7        11.0                    7.0                           8      80000

In [203]:
df['experience']=df.experience.fillna(0)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0                    8.0                           9      50000
1         0.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    8.0                           7      72000
7        11.0                    7.0                           8      80000

In [204]:


# # Change column A's values to floats
# df['experience'] = df['experience'].astype(int)


In [205]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0                    8.0                           9      50000
1         0.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    8.0                           7      72000
7        11.0                    7.0                           8      80000

In [206]:
reg=linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [207]:
reg.predict([[2,9,6]])

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [208]:
reg.predict([[12,10,10]])

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])

In [209]:
reg.predict([[20,10,10]])

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([114505.8224163])

In [210]:
from sklearn.model_selection import train_test_split
X=np.array(df[['experience','test_score(out of 10)','interview_score(out of 10)']])
y=np.array(df['salary($)'])
print(X)
print(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25) 
regr = linear_model.LinearRegression() 
regr.fit(X_train, y_train) 


[[ 0.  8.  9.]
 [ 0.  8.  6.]
 [ 5.  6.  7.]
 [ 2. 10. 10.]
 [ 7.  9.  6.]
 [ 3.  7. 10.]
 [10.  8.  7.]
 [11.  7.  8.]]
[50000 45000 60000 65000 70000 62000 72000 80000]


LinearRegression()

In [211]:
regr.predict([[11,7,8]])

array([76748.27586207])

In [212]:
y_pred=regr.predict(X_test)
print(y_pred)
print(X_test)

[76748.27586207 48995.07389163]
[[11.  7.  8.]
 [ 0.  8.  6.]]


In [213]:
from sklearn.metrics import r2_score
score = r2_score(y_test,y_pred)*100
print(score)

95.66786526224456


In [223]:
regr.predict([[10,10,10]])

array([83255.50082102])

In [226]:
reg.predict([[10,10,10]])

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([86376.27365357])

In [233]:
reg.predict([[2,5,5]])

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([43617.90393013])

In [234]:
regr.predict([[2,5,5]])

array([46407.71756979])