In [63]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import math

In [64]:
df=pd.read_csv('test_scores.csv')
df

name  math  cs
0   david    92  98
1   laura    56  68
2  sanjay    88  81
3     wei    70  80
4    jeff    80  83
5   aamir    49  52
6  venkat    65  66
7   virat    35  30
8  arthur    66  68
9    paul    67  73

In [131]:
def grad_desc(x,y):
    m_curr=b_curr=0
    iterations=100
    n=len(x)
    learning_rate=0.008
    
    cost_previous=0
    for i in range(iterations):
        yp=m_curr*x+b_curr
        cost = (1/n)*sum([value**2 for value in (y-yp)])
        md=-(2/n)*sum(x*(y-yp))
        mb=-(2/n)*sum(y-yp)
        m_curr=m_curr-learning_rate*md
        b_curr=b_curr-learning_rate*mb
        if math.isclose(cost, cost_previous, rel_tol=1e-20):
            break
        cost_previous = cost
        print("m {} , b {} , cost {} , i {}".format(m_curr,b_curr,cost,i))

In [132]:
x = np.array(df.math)
y = np.array(df.cs)
grad_desc(x,y)

m 79.13440000000001 , b 1.1184 , cost 5199.1 , i 0
m -5836.882539520004 , b -82.35994112000002 , cost 28879593.41209627 , i 1
m 436439.1092389523 , b 6158.5362761769 , cost 161405567962.51523 , i 2
m -32627707.890128233 , b -460405.0018588341 , cost 902082854279548.0 , i 3
m 2439217558.540131 , b 34419456.78953996 , cost 5.041669171750294e+18 , i 4
m -182353664631.80585 , b -2573166979.968385 , cost 2.8177487152971883e+22 , i 5
m 13632592510187.02 , b 192367600451.30362 , cost 1.5748172980184994e+26 , i 6
m -1019160097072701.9 , b -14381225156042.686 , cost 8.801528357281899e+29 , i 7
m 7.61914729490489e+16 , b 1075127186197759.0 , cost 4.91910404600645e+33 , i 8
m -5.696004550040318e+18 , b -8.037552113672486e+16 , cost 2.749248043428422e+37 , i 9
m 4.258280694452045e+20 , b 6.008800150284555e+18 , cost 1.536532818497958e+41 , i 10
m -3.183451542821299e+22 , b -4.492123812751546e+20 , cost 8.58755945271894e+44 , i 11
m 2.3799191393594588e+24 , b 3.35827051064993e+22 , cost 4.799518530

C:\Users\hp\AppData\Local\Temp\ipykernel_344\908252626.py:10: RuntimeWarning: overflow encountered in scalar power
  cost = (1/n)*sum([value**2 for value in (y-yp)])


In [107]:
from sklearn import linear_model


In [108]:
reg=linear_model.LinearRegression()
reg.fit(df[['math']],df.cs)
reg

LinearRegression()

In [110]:
reg.predict([[92]])

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([95.54695319])

In [111]:
reg.coef_

array([1.01773624])

In [112]:
reg.intercept_

1.9152193111569176

In [138]:
reg.predict([[67]])

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([70.10354725])