In [146]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt

In [147]:
df=pd.read_csv('insurance_data (1).csv')

In [148]:
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [149]:
#train and test

In [150]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2, random_state=25)

In [151]:
# Preprocessing: Scale the data so that both age and affordibility are in same scaling range

In [152]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

In [153]:
#model building

In [154]:
model=keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_scaled, y_train, epochs=500)

Epoch 1/500


C:\Users\hp\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 843ms/step - accuracy: 0.5000 - loss: 0.7113
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.7110
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5000 - loss: 0.7106
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5000 - loss: 0.7102
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.7098
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.7094
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5000 - loss: 0.7091
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5000 - loss: 0.7087
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5000 - loss: 0.7083
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.7079
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5000 - loss: 0.7076
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.7072


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6874
Epoch 71/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5000 - loss: 0.6871
Epoch 72/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6868
Epoch 73/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.6865
Epoch 74/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6862
Epoch 75/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.6859
Epoch 76/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.6856
Epoch 77/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.6853
Epoch 78/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5000 - loss: 0.6849
Epoch 79/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.6846
Epoch 80/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.6843
Epoch 81/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5000 - loss: 

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5000 - loss: 0.6687
Epoch 139/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6685
Epoch 140/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.6683
Epoch 141/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6680
Epoch 142/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5000 - loss: 0.6678
Epoch 143/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5000 - loss: 0.6675
Epoch 144/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.6673
Epoch 145/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6671
Epoch 146/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6668
Epoch 147/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.6666
Epoch 148/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5000 - loss: 0.6664
Epoch 149/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.50

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5455 - loss: 0.6545
Epoch 207/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5455 - loss: 0.6544
Epoch 208/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5455 - loss: 0.6542
Epoch 209/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5455 - loss: 0.6540
Epoch 210/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5455 - loss: 0.6538
Epoch 211/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5455 - loss: 0.6537
Epoch 212/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5455 - loss: 0.6535
Epoch 213/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5455 - loss: 0.6533
Epoch 214/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5455 - loss: 0.6531
Epoch 215/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5455 - loss: 0.6530
Epoch 216/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5455 - loss: 0.6528
Epoch 217/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.54

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6364 - loss: 0.6441
Epoch 275/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6364 - loss: 0.6440
Epoch 276/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6364 - loss: 0.6438
Epoch 277/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6364 - loss: 0.6437
Epoch 278/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6364 - loss: 0.6436
Epoch 279/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6364 - loss: 0.6435
Epoch 280/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6364 - loss: 0.6433
Epoch 281/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6364 - loss: 0.6432
Epoch 282/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6364 - loss: 0.6431
Epoch 283/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6364 - loss: 0.6430
Epoch 284/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6364 - loss: 0.6428
Epoch 285/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.63

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.6364 - loss: 0.6365
Epoch 343/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.6364 - loss: 0.6364
Epoch 344/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6364 - loss: 0.6363
Epoch 345/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6364 - loss: 0.6362
Epoch 346/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6364 - loss: 0.6361
Epoch 347/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6364 - loss: 0.6361
Epoch 348/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6364 - loss: 0.6360
Epoch 349/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6364 - loss: 0.6359
Epoch 350/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6364 - loss: 0.6358
Epoch 351/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6364 - loss: 0.6357
Epoch 352/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6364 - loss: 0.6356
Epoch 353/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.63

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6364 - loss: 0.6309
Epoch 411/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6364 - loss: 0.6309
Epoch 412/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6364 - loss: 0.6308
Epoch 413/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6364 - loss: 0.6307
Epoch 414/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6364 - loss: 0.6307
Epoch 415/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.6364 - loss: 0.6306
Epoch 416/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.6364 - loss: 0.6305
Epoch 417/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6364 - loss: 0.6305
Epoch 418/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.6364 - loss: 0.6304
Epoch 419/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6364 - loss: 0.6303
Epoch 420/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6364 - loss: 0.6302
Epoch 421/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.63

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6364 - loss: 0.6266
Epoch 479/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6364 - loss: 0.6265
Epoch 480/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6364 - loss: 0.6265
Epoch 481/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6364 - loss: 0.6264
Epoch 482/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6364 - loss: 0.6264
Epoch 483/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6364 - loss: 0.6263
Epoch 484/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6364 - loss: 0.6262
Epoch 485/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6364 - loss: 0.6262
Epoch 486/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6364 - loss: 0.6261
Epoch 487/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6364 - loss: 0.6261
Epoch 488/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6364 - loss: 0.6260
Epoch 489/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.63

In [155]:
X_test_scaled

age  affordibility
2   0.47              1
10  0.18              1
21  0.26              0
11  0.28              1
14  0.49              1
9   0.61              1

In [156]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step


array([[0.66075516],
       [0.60847205],
       [0.451497  ],
       [0.62685424],
       [0.66423655],
       [0.68474233]], dtype=float32)

In [157]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [159]:
coef,intercept=model.get_weights()
coef,intercept

(array([[0.77850705],
        [0.6977987 ]], dtype=float32),
 array([-0.39703578], dtype=float32))

In [160]:
def sigmoid(x):
    import math
    return 1/(1+math.exp(-x))
sigmoid(19)

0.9999999943972036

In [161]:
def prediction_func(age,affordibility):
    weighted_sum=coef[0]*age+coef[1]*affordibility+intercept
    return sigmoid(weighted_sum)

In [162]:
prediction_func(.47,1)

0.6607551707444512

In [163]:
prediction_func(.87,0)

0.5696112868462229

In [164]:
def log_loss(y_true,y_predicted):
    epsilon=1e-15
    y_predicted_new=[max(i,epsilon) for i in y_predicted]
    y_predicted_new=[min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new=np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))



In [165]:
def sigmoid_func(x):
    return 1/(np.exp(-x))

In [173]:
def gradiend_des(age,affordibility,y_true,epochs,loss_thres):
    #w1,w2,bias
    w1=w2=1
    bias=0
    rate=0.5
    n=len(age)
    for i in range(epochs):
        weighted_sum=w1*age+w2*affordibility+bias
        y_pred=sigmoid_func(weighted_sum)
        loss=log_loss(y_true,y_pred)
        w1d=(1/n)*np.dot(np.transpose(age),(y_pred-y_true))
        w2d=(1/n)*np.dot(np.transpose(affordibility),(y_pred-y_true))
        biasd=np.mean(y_pred-y_true)
        w1=w1-rate*w1d
        w2=w2-rate*w2d
        bias=bias-rate*biasd
        
        if(loss<=loss_thres):
            print(f'epoch {i} , w1 {w1} , w2 {w2} ,bias {bias} , loss : {loss}')
            break;
        
        if(i%50==0):
             print(f'epoch {i} , w1 {w1} , w2 {w2} ,bias {bias} , loss : {loss}')
            
            
        
        
        
    

In [174]:
gradiend_des(X_train_scaled['age'],X_train_scaled['affordibility'],y_train,500,0.6253)

epoch 0 , w1 0.4247034322281562 , w2 -0.13343469456612933 ,bias -1.3530049636058623 , loss : 17.26978799617044
epoch 5 , w1 0.6370246890861313 , w2 0.23372676966614922 ,bias -1.0950745497553238 , loss : 0.6088937423236589


In [175]:
np.dot([1,2,3],[4,5,6])

32

In [176]:
class myNN:
    def __init__(self):
        self.w1=1
        self.w2=1
        self.bias=0
    def gradiend_des(self,age,affordibility,y_true,epochs,loss_thres):
    #w1,w2,bias
        w1=w2=1
        bias=0
        rate=0.5
        n=len(age)
        for i in range(epochs):
            weighted_sum=w1*age+w2*affordibility+bias
            y_pred=sigmoid_func(weighted_sum)
            loss=log_loss(y_true,y_pred)
            w1d=(1/n)*np.dot(np.transpose(age),(y_pred-y_true))
            w2d=(1/n)*np.dot(np.transpose(affordibility),(y_pred-y_true))
            biasd=np.mean(y_pred-y_true)
            w1=w1-rate*w1d
            w2=w2-rate*w2d
            bias=bias-rate*biasd
            
            if(i%50==0):
                print(f'epoch {i} , w1 {w1} , w2 {w2} ,bias {bias} , loss : {loss}')
                
                
            
            if(loss<=loss_thres):
                print(f'epoch {i} , w1 {w1} , w2 {w2} ,bias {bias} , loss : {loss}')
                break;
            
           
                

            
            
         
        
        return w1,w2,bias


        
        
        
    def fit(self,X,y,epochs,loss_thres):
        self.w1,self.w2,self.bias=self.gradiend_des(X['age'],X['affordibility'],y,epochs,loss_thres)
    
    def predict(self,X_test):
        weight_sum=X_test['age']*self.w1+X_test['affordibility']*self.w2+self.bias
        return sigmoid_func(weight_sum)
        
        

In [177]:
model=myNN()
model.fit(X_train_scaled,y_train,epochs=500,loss_thres=0.6253)

epoch 0 , w1 0.4247034322281562 , w2 -0.13343469456612933 ,bias -1.3530049636058623 , loss : 17.26978799617044
epoch 5 , w1 0.6370246890861313 , w2 0.23372676966614922 ,bias -1.0950745497553238 , loss : 0.6088937423236589


In [178]:
model.predict(X_test_scaled)

2     0.570098
10    0.473936
21    0.394772
11    0.505109
14    0.577408
9     0.623278
dtype: float64

In [179]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [180]:
coef,intercept

(array([[0.77850705],
        [0.6977987 ]], dtype=float32),
 array([-0.39703578], dtype=float32))