In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('insurance_data (1).csv')

In [3]:
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [4]:
#train and test

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2, random_state=25)

In [6]:
# Preprocessing: Scale the data so that both age and affordibility are in same scaling range

In [7]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

In [8]:
#model building

In [ ]:
model=keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_scaled, y_train, epochs=100)

In [10]:
X_test_scaled

age  affordibility
2   0.47              1
10  0.18              1
21  0.26              0
11  0.28              1
14  0.49              1
9   0.61              1

In [11]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step


array([[0.64471424],
       [0.56694895],
       [0.40433905],
       [0.5943529 ],
       [0.64985454],
       [0.6799389 ]], dtype=float32)

In [12]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [13]:
coef,intercept=model.get_weights()
coef,intercept

(array([[1.1257616],
        [0.7468925]], dtype=float32),
 array([-0.680116], dtype=float32))

In [14]:
def sigmoid(x):
    import math
    return 1/(1+math.exp(-x))
sigmoid(19)

0.9999999943972036

In [15]:
def prediction_func(age,affordibility):
    weighted_sum=coef[0]*age+coef[1]*affordibility+intercept
    return sigmoid(weighted_sum)

In [16]:
prediction_func(.47,1)

0.6447141817015378

In [17]:
prediction_func(.87,0)

0.5742705601183442

In [36]:
def log_loss(y_true,y_predicted):
    epsilon=1e-15
    y_predicted_new=[max(i,epsilon) for i in y_predicted]
    y_predicted_new=[min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new=np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))



In [37]:
def sigmoid_func(x):
    return 1/(np.exp(-x))

In [43]:
def gradiend_des(age,affordibility,y_true,epochs,loss_thres):
    #w1,w2,bias
    w1=w2=1
    bias=0
    rate=0.5
    n=len(age)
    for i in range(epochs):
        weighted_sum=w1*age+w2*affordibility+bias
        y_pred=sigmoid_func(weighted_sum)
        loss=log_loss(y_true,y_pred)
        w1d=(1/n)*np.dot(np.transpose(age),(y_pred-y_true))
        w2d=(1/n)*np.dot(np.transpose(affordibility),(y_pred-y_true))
        biasd=np.mean(y_pred-y_true)
        w1=w1-rate*w1d
        w2=w2-rate*w2d
        bias=bias-rate*biasd
        
        if(loss<=loss_thres):
            break;
        
        print(f'epoch {epochs} , w1 {w1} , w2 {w2} ,bias {bias} , loss : {loss}')
            
            
        
        
        
    

In [44]:
gradiend_des(X_train_scaled['age'],X_train_scaled['affordibility'],y_train,5000,0.4631)

epoch 5000 , w1 0.4247034322281562 , w2 -0.13343469456612933 ,bias -1.3530049636058623 , loss : 17.26978799617044
epoch 5000 , w1 0.4917472031258109 , w2 -0.015283941449960162 ,bias -1.2443883228831265 , loss : 0.7882596566096225
epoch 5000 , w1 0.544623996539505 , w2 0.07766482198762645 ,bias -1.168846683468526 , loss : 0.7083698580689958
epoch 5000 , w1 0.5846134959788039 , w2 0.1470480256443373 ,bias -1.1231689827521762 , loss : 0.656746085339281
epoch 5000 , w1 0.6143878830030411 , w2 0.19727154057942245 ,bias -1.1009868152415272 , loss : 0.6262201715800854
epoch 5000 , w1 0.6370246890861313 , w2 0.23372676966614922 ,bias -1.0950745497553238 , loss : 0.6088937423236589
epoch 5000 , w1 0.6551553650840075 , w2 0.2611561156358429 ,bias -1.0992988674243567 , loss : 0.5987533777069681
epoch 5000 , w1 0.6706427753885925 , w2 0.2829775106446335 ,bias -1.1093373025509239 , loss : 0.592248530103403
epoch 5000 , w1 0.6846564717379885 , w2 0.30136964829864654 ,bias -1.1224853566062936 , loss 

In [45]:
np.dot([1,2,3],[4,5,6])

32