In [33]:
import numpy as np

In [34]:
y_pred=np.array([1,1,0,0,1])
y_true=np.array([0.30,0.7,1,0,.5])

In [35]:
def mae(y_true,y_pred):
    total_error=0
    for y_t,y_p in zip(y_true,y_pred):
        total_error+=abs(y_t-y_p)
    
    print("error",total_error)
    print("mae",total_error/len(y_true))

In [36]:
mae(y_true,y_pred)

error 2.5
mae 0.5


In [37]:
np.log([1])

array([0.])

In [38]:
epsilon=1e-15

In [39]:
y_pred

array([1, 1, 0, 0, 1])

In [40]:
y_pred_new=[max(i,epsilon) for i in y_pred]

In [41]:
y_pred_new

[1, 1, 1e-15, 1e-15, 1]

In [42]:
y_pred_new=[min(i,1-epsilon) for i in y_pred_new]

In [43]:
y_pred_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [44]:
y_pred_new=np.array(y_pred_new)

In [45]:
y_pred_new

array([1.e+00, 1.e+00, 1.e-15, 1.e-15, 1.e+00])